
@url = http://localhost:3000/api
###

GET {{url}}/test
###



// -----------------
// U S E R
// -----------------

// Register empleado

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "Ricardo",
	"email": "ricardo@labor.com",
	"password": "1234",
	"province": "Valencia",
	"city": "Valencia",
	"is_company": false,
	"name": "Ricardo",
	"surname": "Salas",
	"nif": "25774146S",
	"phone": "647009123",
	"website": "www.asd.es",
	"description": "test"
}
###



// Register empresa

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "Empresa01",
	"email": "empresa01@labor.es",
	"password": "1234",
	"sector": "IT",
	"is_company": true,
	"name": "Empresa 01",
	"cif": "25774146S",
	"phone": "647009123",
	"website": "www.empresa01.es",
	"description": "Soy la empresa 01"
}
###



// Perfil de usuario

GET {{url}}/user/e5e32e93c666da
###



// Login
# @name resLogin

POST {{url}}/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###



@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}



// Logout
GET {{url}}/user/logout?token={{token}}
###
